# Projet ML

In [78]:
import pandas as pd
import numpy as np
import matplotlib as mp

# Dataset Regression 

Real estate valuation data set Data Set


lien: https://archive.ics.uci.edu/ml/datasets/Real+estate+valuation+data+set?fbclid=IwAR0yTDnyUu7Cae-1x9aGzdMSCfmttogCWEJ_i8DA48qaW8xgL3CDS_hOUis

In [37]:
df1 = pd.read_excel("Real estate valuation data set.xlsx")
# vous devez télécharger ce fichier et l'uploader sur anaconda

In [4]:
df1.head()

No  X1 transaction date  X2 house age  \
0   1          2012.916667          32.0   
1   2          2012.916667          19.5   
2   3          2013.583333          13.3   
3   4          2013.500000          13.3   
4   5          2012.833333           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [5]:
df1.tail()

No  X1 transaction date  X2 house age  \
409  410          2013.000000          13.7   
410  411          2012.666667           5.6   
411  412          2013.250000          18.8   
412  413          2013.000000           8.1   
413  414          2013.500000           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9

In [6]:
df1.shape

(414, 8)

# On commence par travailler sur le dataset de type regression df1

In [11]:
df1.rename(
    columns={
        "X1 transaction date": "Transaction_Date", 
        "X2 house age": "House_Age", 
        "X3 distance to the nearest MRT station": "Distance",
        "X4 number of convenience stores": "Num_Stores_NearBy",
        "X5 latitude": "Latitude",
        "X6 longitude": "Longitude",
        "Y house price of unit area": "Target",
    },
    inplace = True
)

In [12]:
df1.head()

No  Transaction_Date  House_Age   Distance  Num_Stores_NearBy  Latitude  \
0   1       2012.916667       32.0   84.87882                 10  24.98298   
1   2       2012.916667       19.5  306.59470                  9  24.98034   
2   3       2013.583333       13.3  561.98450                  5  24.98746   
3   4       2013.500000       13.3  561.98450                  5  24.98746   
4   5       2012.833333        5.0  390.56840                  5  24.97937   

   Longitude  Target  
0  121.54024    37.9  
1  121.53951    42.2  
2  121.54391    47.3  
3  121.54391    54.8  
4  121.54245    43.1

In [13]:
df1.shape

(414, 8)

# Normal equation (NE)

on enleve la colonne No avec la fonction drop et ajouter axis=1 pour supprimer la colonne

In [14]:
import pandas as pd
import numpy as np

dataenleverno= df1.drop('No',axis=1) #enlever la colonne No qui est en plus et pour faciliter le travail
dataenlevertarget= dataenleverno.drop('Target',axis=1)  # enlever la colonne Target pour preparer la matrice X 

dataenlevertarget= pd.DataFrame(dataenlevertarget)

display(dataenlevertarget)

arrayprepareX= dataenlevertarget.to_numpy()   # convertir la dataframe dataenlevertarget en array pour faire des opérations de numpy plus tard

X0= np.ones((414,1)) # préparer la colonne X0 qui contient que des 1  pour l'ajouter à la matrice prepare X et avoir X 
X0

Transaction_Date  House_Age    Distance  Num_Stores_NearBy  Latitude  \
0         2012.916667       32.0    84.87882                 10  24.98298   
1         2012.916667       19.5   306.59470                  9  24.98034   
2         2013.583333       13.3   561.98450                  5  24.98746   
3         2013.500000       13.3   561.98450                  5  24.98746   
4         2012.833333        5.0   390.56840                  5  24.97937   
..                ...        ...         ...                ...       ...   
409       2013.000000       13.7  4082.01500                  0  24.94155   
410       2012.666667        5.6    90.45606                  9  24.97433   
411       2013.250000       18.8   390.96960                  7  24.97923   
412       2013.000000        8.1   104.81010                  5  24.96674   
413       2013.500000        6.5    90.45606                  9  24.97433   

     Longitude  
0    121.54024  
1    121.53951  
2    121.54391  
3    121.54391  
4    121.54245  
..         ...  
409  121.50381  
410  121.54310  
411  121.53986  
412  121.54067  
413  121.54310  

[414 rows x 6 columns]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [15]:
dataenlevertarget.shape

(414, 6)

In [16]:
import pandas as pd
import numpy as np

X= np.append(X0, arrayprepareX , axis=1) #preparer la matrice X
X

array([[1.00000000e+00, 2.01291667e+03, 3.20000000e+01, ...,
        1.00000000e+01, 2.49829800e+01, 1.21540240e+02],
       [1.00000000e+00, 2.01291667e+03, 1.95000000e+01, ...,
        9.00000000e+00, 2.49803400e+01, 1.21539510e+02],
       [1.00000000e+00, 2.01358333e+03, 1.33000000e+01, ...,
        5.00000000e+00, 2.49874600e+01, 1.21543910e+02],
       ...,
       [1.00000000e+00, 2.01325000e+03, 1.88000000e+01, ...,
        7.00000000e+00, 2.49792300e+01, 1.21539860e+02],
       [1.00000000e+00, 2.01300000e+03, 8.10000000e+00, ...,
        5.00000000e+00, 2.49667400e+01, 1.21540670e+02],
       [1.00000000e+00, 2.01350000e+03, 6.50000000e+00, ...,
        9.00000000e+00, 2.49743300e+01, 1.21543100e+02]])

In [26]:
import pandas as pd
import numpy as np

Y = dataenleverno['Target']   # Préparer le vecteur Y de taille m=414 et 1 colonne
Y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Target, Length: 414, dtype: float64

In [27]:
Xtrps= X.T # la transosé de X 
Xtrps

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [2.01291667e+03, 2.01291667e+03, 2.01358333e+03, ...,
        2.01325000e+03, 2.01300000e+03, 2.01350000e+03],
       [3.20000000e+01, 1.95000000e+01, 1.33000000e+01, ...,
        1.88000000e+01, 8.10000000e+00, 6.50000000e+00],
       ...,
       [1.00000000e+01, 9.00000000e+00, 5.00000000e+00, ...,
        7.00000000e+00, 5.00000000e+00, 9.00000000e+00],
       [2.49829800e+01, 2.49803400e+01, 2.49874600e+01, ...,
        2.49792300e+01, 2.49667400e+01, 2.49743300e+01],
       [1.21540240e+02, 1.21539510e+02, 1.21543910e+02, ...,
        1.21539860e+02, 1.21540670e+02, 1.21543100e+02]])

In [28]:
xtrps_dot_X= Xtrps.dot(X)      # X X.T
xtrps_dot_X

array([[4.14000000e+02, 8.33443667e+05, 7.33300000e+03, 4.48728675e+05,
        1.69500000e+03, 1.03371784e+04, 5.03148115e+04],
       [8.33443667e+05, 1.67784628e+09, 1.47624446e+07, 9.03366612e+08,
        3.41229075e+06, 2.08102800e+07, 1.01291210e+08],
       [7.33300000e+03, 1.47624446e+07, 1.83488940e+05, 8.10028636e+06,
        3.07101000e+04, 1.83101075e+05, 8.91200633e+05],
       [4.48728675e+05, 9.03366612e+08, 8.10028636e+06, 1.14424681e+09,
        9.12091717e+05, 1.12004963e+07, 5.45290538e+07],
       [1.69500000e+03, 3.41229075e+06, 3.07101000e+04, 9.12091717e+05,
        1.05230000e+04, 4.23292113e+04, 2.06007432e+05],
       [1.03371784e+04, 2.08102800e+07, 1.83101075e+05, 1.12004963e+07,
        4.23292113e+04, 2.58109383e+05, 1.25631207e+06],
       [5.03148115e+04, 1.01291210e+08, 8.91200633e+05, 5.45290538e+07,
        2.06007432e+05, 1.25631207e+06, 6.11492825e+06]])

In [29]:
temp_1=np.linalg.inv(xtrps_dot_X)  # inv(X X.T)
temp_1

array([[ 5.85119199e+05, -5.69794948e+01, -4.51740380e-02,
        -4.08172094e-02, -1.72975746e-01, -8.98188612e+02,
        -3.68572328e+03],
       [-5.69794957e+01,  3.08947371e-02, -4.67950572e-06,
        -1.37054365e-06, -1.78176627e-04, -7.37838069e-02,
        -2.77422100e-02],
       [-4.51740369e-02, -4.67950589e-06,  1.89222965e-05,
        -1.46882500e-08, -6.30666641e-06, -1.55049788e-03,
         7.65350234e-04],
       [-4.08172092e-02, -1.37054372e-06, -1.46882499e-08,
         6.57112052e-09,  6.33334256e-07,  1.64232503e-04,
         3.24735003e-04],
       [-1.72975733e-01, -1.78176629e-04, -6.30666641e-06,
         6.33334255e-07,  4.51262588e-04, -1.25880883e-02,
         6.94099019e-03],
       [-8.98188617e+02, -7.37838078e-02, -1.55049788e-03,
         1.64232504e-04, -1.25880883e-02,  2.53150728e+01,
         3.41087077e+00],
       [-3.68572326e+03, -2.77422169e-02,  7.65350239e-04,
         3.24735003e-04,  6.94099027e-03,  3.41087072e+00,
         3.0082377

In [30]:
temp_2= Xtrps.dot(Y)  # X.T Y 
temp_2

array([1.57238000e+04, 3.16544902e+07, 2.65028290e+05, 1.22652707e+07,
       7.38280000e+04, 3.92646134e+05, 1.91101139e+06])

In [32]:
Teta = temp_1.dot(temp_2)  # INV(x X.T)* (x.T Y) = temp_1* temp_2
Teta

array([-1.44419821e+04,  5.14901703e+00, -2.69696734e-01, -4.48750827e-03,
        1.13332498e+00,  2.25470142e+02, -1.24290627e+01])

In [33]:
teta0= Teta[0]
teta1= Teta[1]
teta2= Teta[2]
teta3= Teta[3]
teta4= Teta[4]
teta5= Teta[5]
teta6= Teta[6]

print(teta0)
print(teta1)
print(teta2)
print(teta3)
print(teta4)
print(teta5)
print(teta6)



-14441.982132911682
5.149017027419177
-0.26969673445114495
-0.004487508266947771
1.1333249825001985
225.47014214843512
-12.429062716662884


In [34]:
def pred_value(teta0,teta1,teta2,teta3,teta4,teta5,teta6,Transaction_Date,House_Age,Distance,Num_Stores_NearBy,Latitude,Longitude):
    prediction_value= teta0+ teta1*Transaction_Date+ teta2*House_Age+ teta3*Distance+ teta4*Num_Stores_NearBy+ teta5*Latitude+ teta6*Longitude
    return prediction_value

In [35]:

Transaction_Date=2012.916667
House_Age= 32.0
Distance= 84.87882
Num_Stores_NearBy= 10
Latitude= 24.98298
Longitude= 121.54024

print (pred_value(teta0,teta1,teta2,teta3,teta4,teta5,teta6,Transaction_Date,House_Age,Distance,Num_Stores_NearBy,Latitude,Longitude))
#0	1	2012.916667	32.0	84.87882	10	24.98298	121.54024	37.9

47.16690649655402


In [36]:
Transaction_Date=2012.916667
House_Age= 19.5
Distance= 306.59470
Num_Stores_NearBy= 9
Latitude= 24.98034
Longitude= 121.53951

print (pred_value(teta0,teta1,teta2,teta3,teta4,teta5,teta6,Transaction_Date,House_Age,Distance,Num_Stores_NearBy,Latitude,Longitude))

#1	2	2012.916667	19.5	306.59470	9	24.98034	121.53951	42.2

47.82367089079139


In [37]:
Transaction_Date=2013.583333
House_Age= 13.3
Distance= 561.98450
Num_Stores_NearBy= 5
Latitude= 24.98746
Longitude= 121.54391

print (pred_value(teta0,teta1,teta2,teta3,teta4,teta5,teta6,Transaction_Date,House_Age,Distance,Num_Stores_NearBy,Latitude,Longitude))

#2	3	2013.583333	13.3	561.98450	5	24.98746	121.54391	47.3

48.7997609973379


In [38]:
Transaction_Date=2013.000000
House_Age= 13.7
Distance= 4082.01500
Num_Stores_NearBy= 0
Latitude= 24.94155
Longitude= 121.50381

print (pred_value(teta0,teta1,teta2,teta3,teta4,teta5,teta6,Transaction_Date,House_Age,Distance,Num_Stores_NearBy,Latitude,Longitude))

#409	2013.000000	13.7	4082.01500	0	24.94155	121.50381	15.4

14.372571061646113


# Préprocessing

## Dataset regression Real estate valuation

# 1- Missing values 

Dans la description du dataset regression c'est mentionnée qu'il y a pas de missing value
et il existe une commende qui nous permet de bien détermier si oui ou non il y a des missing values qui est:

df1 .isna().sum()

In [22]:
df1.isna().sum()
# comme vous pouvez le remarquer tous les valeurs obtenues sont égales à zero par conséquent il n'y a pas de missing values

No                   0
Transaction_Date     0
House_Age            0
Distance             0
Num_Stores_NearBy    0
Latitude             0
Longitude            0
Target               0
dtype: int64

In [19]:
df1.dtypes

No                     int64
Transaction_Date     float64
House_Age            float64
Distance             float64
Num_Stores_NearBy      int64
Latitude             float64
Longitude            float64
Target               float64
dtype: object

In [43]:
df1.columns

Index(['No', 'Transaction_Date', 'House_Age', 'Distance', 'Num_Stores_NearBy',
       'Latitude', 'Longitude', 'Target'],
      dtype='object')

# 2- Enlever un  attribut non nécéessaire comme l'attribut "No"

In [53]:
df1= df1.drop('No',axis=1)
df1

Transaction_Date  House_Age    Distance  Num_Stores_NearBy  Latitude  \
0         2012.916667       32.0    84.87882                 10  24.98298   
1         2012.916667       19.5   306.59470                  9  24.98034   
2         2013.583333       13.3   561.98450                  5  24.98746   
3         2013.500000       13.3   561.98450                  5  24.98746   
4         2012.833333        5.0   390.56840                  5  24.97937   
..                ...        ...         ...                ...       ...   
409       2013.000000       13.7  4082.01500                  0  24.94155   
410       2012.666667        5.6    90.45606                  9  24.97433   
411       2013.250000       18.8   390.96960                  7  24.97923   
412       2013.000000        8.1   104.81010                  5  24.96674   
413       2013.500000        6.5    90.45606                  9  24.97433   

     Longitude  Target  
0    121.54024    37.9  
1    121.53951    42.2  
2    121.54391    47.3  
3    121.54391    54.8  
4    121.54245    43.1  
..         ...     ...  
409  121.50381    15.4  
410  121.54310    50.0  
411  121.53986    40.6  
412  121.54067    52.5  
413  121.54310    63.9  

[414 rows x 7 columns]